<?php

/**
* Implements hook_block_info().
*/
function librarydams_customizations_block_info() {
  $blocks = array();
  $blocks['mods_metadata'] = array(
    'info' => t('MODS metadata'),
  );
  return $blocks;
}

/**
* Implements hook_block_view().
*/
function librarydams_customizations_block_view($block_name = '') {
  if ($block_name == 'mods_metadata') {
    $block = array();
    // Is there a better way to do this?
    if (arg(2)) {
      $object_id = arg(2);
      $datastream = islandora_datastream_load('MODS', $object_id);
      if (is_object($datastream) && $datastream->id === 'MODS') {
        $islandora_object = islandora_object_load($object_id);
        $content = islandora_mods_display_display_callback($islandora_object);
        $block = array(
          'subject' => t('MODS Metadata'),
          'content' => $content,
        );
      }
    }
    return $block;
  }
}

/**
 * Implements hook_preprocess_html().
 */
function librarydams_customizations_preprocess_html(&$variables) {
// Add conditional stylesheets for admin pages on admin theme.
  if (path_is_admin(current_path())) {
    drupal_add_css(drupal_get_path('module', 'librarydams_customizations') . '/css/admin.css', array('weight' => CSS_THEME));
  }
}

/**
 * Callback from form to validate terms in an autocompleted text field
 */
function librarydams_customizations_taxonomy_validate($element, &$form_state) {
  if (isset($element['#autocomplete_path'])) {
    $field = str_replace('taxonomy/autocomplete/', '', $element['#autocomplete_path']);
    $allowed = taxonomy_allowed_values(field_info_field($field));
    if (($element['#value'] !== '') && (!in_array($element['#value'], $allowed))) {
      form_error($element, t($element['#title']) . ' - ' . t('Please select a term from the autocomplete list.'));
    }
  }
}
